### ISSUE TITLE
[💡Feature Request] Additions

### ISSUE THREAD

**Issue by alexonab** [tfukaza/harvest#218]
- [x] #239

I'm not sure if the below are better suited to be defined as part of a strategy or implemented in Harvest.

Order management in strategy
on_open
on_close
on_fill

Risk Management
account pnl
track wins
track losses
stop after max trades
exit only after max loss
stop trading after max gains
day trade warning
good faith violation/trading on unsettled funds warning

Asset
is_option
is_stock

Broker
market_is_open (Crypto, stock, option, etc)
per asset fees
cancel order method

Position
pnl
bars since open
exit time
exit reason

**Comment by tfukaza** [comment]
Some of the features can't be implemented because how the framework is designed, or simply because it's too complicated for the current scale of this project. That being said, I think we can implement the following (I'm open to comments though):

## Risk Management
- [ ] account pnl
- [ ] day trade warning

## Asset
- [ ] is_option
- [ ] is_stock
- [ ] is_crypto

## Broker
- [ ] market_is_open (Crypto, stock, option, etc)
- [ ] per asset fees
- [ ] cancel order method

## Position
- [ ] pnl
