### ISSUE TITLE
Plugin feature

### ISSUE THREAD

**Issue by tfukaza** [tfukaza/harvest#93]
Trying to add every feature under the sun can bloat the core functionalities of the framework and create an excessively large dependance tree. The solution is to split out certain features as "plugins" that the users can install if they want to use. One way to do this would be to create a class called `Plugin` which when added to `Trader` defines additional methods the user can call. The exact implementation is up for debate, but it should follow these principles:
- Plugins can be installed and added easily, possibly using a method like `set_plugin()`
- Any dependencies of the plugins are not part of the dependance tree of harvest itself. Users should install them on their own after installing Harvest.
 
Possible plugins that may be developed in the future include:
- ML/DNN integration
- Earning report data of companies 
- etc.

TODO:
- [ ] Define the plugin class/interface
- [ ] Revive the Yahoo Earnings Plugin in `plugin/yahoo.py`

**Comment by shershah010** [comment]
What is the Plugin feature supposed to do exactly?What other plugins to you see implemented in the future?

**Comment by shershah010** [comment]
I was thinking more about this and have a few questions:
1. Should plugins be allowed to import other harvest modules such as `Storage`? Because if so then could a plugin be a more complex `Algo` that does ML?
2. Should third-parties be allowed to create plugins without needing to know the internals of `Harvest`?
3. Should we move parts of `Harvest` that require excessive dependencies into the plugins? For example the database storage can be moved to the `plugins` since it uses the `SQLAlchemy` dependencies. I guess this become problematic when deciding where new streamers and brokers would go since they usually require extra plugins.
4. How would a plugin like `Yahoo Earnings Plugin` work? Where in `Harvest` will it be called and where is the output of the plugin go?

**Comment by tfukaza** [comment]
I would say...
1. Why not :)
2. Definitely yes, being easy to mod is harvest's strength.
3. To some extend this can be solved by using `extras_require` in `setup.py`
4. Ideally "installing" the plugin will add a new interface to the `Algo` class which the user can call just like any other function.
